<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_LISTER_fas fa-star filled-star</name>
   <tag></tag>
   <elementGuidId>5efca7a4-37cf-4367-a4f1-155325173235</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/persistgate/div/div[3]/div/div/div[2]/div/div/div/i[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>23446aea-9c29-499f-a849-354f033a33f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-star filled-star</value>
      <webElementGuid>33152ad2-4447-4a17-9869-83c7ec8d7ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/persistgate[1]/div[@class=&quot;App&quot;]/div[@class=&quot;ListingInfo&quot;]/div[@class=&quot;Details-wrapper&quot;]/div[@class=&quot;Details-Container&quot;]/div[@class=&quot;ListingRight&quot;]/div[@class=&quot;TopPart&quot;]/div[@class=&quot;ListerInfo&quot;]/div[@class=&quot;Listing-rating&quot;]/i[@class=&quot;fas fa-star filled-star&quot;]</value>
      <webElementGuid>1d3ae5ed-77cf-4d5c-854f-f591df8b94f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/persistgate/div/div[3]/div/div/div[2]/div/div/div/i[3]</value>
      <webElementGuid>f9878108-2a8a-4094-8851-a6ee94140c2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i[3]</value>
      <webElementGuid>145a60a0-4281-4122-9381-ba839f8958ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
