<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>496d8c64-7803-4341-92e3-7e91eab6adf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/persistgate/div/div[4]/div/div/div[5]/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.Socialmedia > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e7385daa-ab7d-4c73-b0b7-8bce94dc5bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/facebook.e6b2fb939c2985b6292f.png</value>
      <webElementGuid>f69488de-626f-48b3-b2e9-d96d1fbe1583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/persistgate[1]/div[@class=&quot;App&quot;]/div[@class=&quot;ContaineraLL&quot;]/div[@class=&quot;FooterContainer&quot;]/div[@class=&quot;Footer&quot;]/div[@class=&quot;GetInTouch&quot;]/div[@class=&quot;Socialmedia&quot;]/img[1]</value>
      <webElementGuid>1d7e55dd-583d-4305-af8a-f0a848ba3dbb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/persistgate/div/div[4]/div/div/div[5]/div/img</value>
      <webElementGuid>220b009f-7c47-4747-9631-f8ca07b9ab52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/img</value>
      <webElementGuid>7fb03e89-ea1b-42ae-bf9d-5cdd8f3a04c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/media/facebook.e6b2fb939c2985b6292f.png']</value>
      <webElementGuid>79e16774-579e-48eb-9963-c9c4e9822c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/persistgate/div/div/div[2]/img</value>
      <webElementGuid>d87363c7-7ba8-49d0-bc55-1e086dcfb242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>588321a6-7930-47a8-9779-ef89e4f67f11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://res.cloudinary.com/dbjv7n54i/image/upload/v1734348310/Userimages/piir1elqm1qpqw0xa5eg.jpg')]</value>
      <webElementGuid>a36ac122-8b4d-450d-8dc2-cd276c081670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://res.cloudinary.com/dbjv7n54i/image/upload/v1734348310/Userimages/piir1elqm1qpqw0xa5eg.jpg']</value>
      <webElementGuid>971bdeab-cbc2-48c2-9825-8d506c00977c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://res.cloudinary.com/dbjv7n54i/image/upload/v1734289721/Userimages/bieswi5txlbwpf5bw4ge.jpg')]</value>
      <webElementGuid>fe230427-cbca-40a0-ba1a-c9ac5df38fff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://res.cloudinary.com/dbjv7n54i/image/upload/v1734289721/Userimages/bieswi5txlbwpf5bw4ge.jpg']</value>
      <webElementGuid>8effd07b-da61-4de6-9a5a-2a5dba836906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://res.cloudinary.com/dbjv7n54i/image/upload/v1734289596/Userimages/dpafqopcwuucor3ctood.jpg')]</value>
      <webElementGuid>9fb1e7c5-3020-4639-856a-34b4b8c9bd3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://res.cloudinary.com/dbjv7n54i/image/upload/v1734289596/Userimages/dpafqopcwuucor3ctood.jpg']</value>
      <webElementGuid>df4be0ed-2104-416d-9c50-94801106601a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://res.cloudinary.com/dbjv7n54i/image/upload/v1715199215/Userimages/pstavytcf9sbdxlnrxzt.jpg')]</value>
      <webElementGuid>bd4e8722-e1db-4745-8e70-65d7e1279d9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://res.cloudinary.com/dbjv7n54i/image/upload/v1715199215/Userimages/pstavytcf9sbdxlnrxzt.jpg']</value>
      <webElementGuid>d4c98fe6-baea-43ee-81a4-d61ae65a2b4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
