<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pickup Location_PickupLocation</name>
   <tag></tag>
   <elementGuidId>5ac6cd45-da23-4378-954a-a6f5d8bbf430</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PickupDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PickupDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a37dfe10-b3e7-441f-938d-29a8771fb441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>92c1fadd-59bc-4348-a5ad-7e71a7f0f99f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PickupDate</value>
      <webElementGuid>cbc68b0e-59f4-481f-b2d1-5b9ddc798d50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PickupLocation</value>
      <webElementGuid>7722524e-6663-4d9f-890a-4a9e3a77d2f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PickupDate&quot;)</value>
      <webElementGuid>5a589dc7-ecad-4daa-a843-a918f547148a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PickupDate']</value>
      <webElementGuid>afbb36f2-001c-42d6-a478-85d84cd71497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/persistgate/div/div[3]/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>94e18c81-26aa-4df8-bfd7-00e8edcbf4c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>c21edc06-ae15-4a06-8ac2-a35912b2d367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'PickupDate' and @name = 'PickupLocation']</value>
      <webElementGuid>0eae9dec-b9bd-461e-940d-a624ca03a000</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
