<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login_login_password</name>
   <tag></tag>
   <elementGuidId>9e892d00-0492-4e03-b3b4-eaf2bc47ea24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='login_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6a9fde13-2db3-4d75-8b59-69781f167df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login_password</value>
      <webElementGuid>1110c595-aa6f-4af0-9067-40f7f70cb706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>fa28ea79-dcbb-48c4-942c-ab51e27de5bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>754b3925-8459-4ab4-b7e8-e9960edb81f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_password&quot;)</value>
      <webElementGuid>5029352d-b741-4760-a7f1-67ce0f2ea17e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a17f4cb9-099e-425c-bf56-f4815e5446dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='login_password']</value>
      <webElementGuid>2c65ab6d-c1e6-411e-8712-226c9fe46d4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/persistgate/div/div[3]/div/div/div[2]/form/div[2]/input</value>
      <webElementGuid>609ea69e-9c1a-496d-83c7-860166aaac98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div[2]/input</value>
      <webElementGuid>aa6d982e-ecd0-47ee-807f-f260910ddb62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'login_password' and @type = 'password' and @placeholder = 'password']</value>
      <webElementGuid>cecf5f14-6854-4491-86ca-2a00d1a8db91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
